{
 "title": "Luxor Relay Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Outbound Hashrate",
   "type": "stat",
   "description": "Rolling hashrate (with a 10m minimum interval). The scalar value is determined by the global timerange.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "THs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(backend_outbound_shares_diff{share_type=\"valid\"}[$__interval])) * 2 ^ 32 / 1e12"
    }
   ]
  },
  {
   "title": "Outbound Share Efficiency",
   "type": "stat",
   "description": "This is the share efficiency we that care about the most. This is the recorded efficiency based on responses from the pool. We use this as the final determination of whether or not we pay for the share.",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (share_type)(increase(backend_outbound_shares{share_type=\"valid\"}[$__range])) / ignoring(share_type) group_left sum(increase(backend_outbound_shares[$__range]))"
    }
   ]
  },
  {
   "title": "Active Backend Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (backend_name) (backend_up)",
     "legendFormat": "{{backend_name}}"
    }
   ]
  },
  {
   "title": "Go Memory",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "go_memstats_sys_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Share Validations (backend_outbound_shares)",
   "type": "graph",
   "description": "1m minimum intervals stacked bar chart showing proportion of valid, invalid, and stale shares.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (share_type)(increase(backend_outbound_shares[$__interval])) / ignoring(share_type) group_left sum(increase(backend_outbound_shares[$__interval]))",
     "legendFormat": "{{share_type}}"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(proxy_worker_up) without (worker_addr, job, instance, pod) != 0"
    }
   ]
  },
  {
   "title": "Valid Hashrate By Backend (backend_outbound_shares_diff)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "THs", "label": "TH" }
   ],
   "targets": [
    {
     "expr": "(sum by (backend_name) (rate(backend_outbound_shares_diff[$__interval]))) * 2 ^ 32 / 1e12",
     "legendFormat": "{{backend_name}}"
    }
   ]
  }
 ]
}