{
 "title": "Luxor Relay Metrics - User",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user",
    "query": "label_values(proxy_worker_difficulty, user)"
   },
   {
    "name": "worker",
    "query": "label_values(proxy_worker_difficulty{user=~\"$user\"}, worker)"
   }
  ]
 },
 "panels": [
  {
   "title": "Workers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (user) (proxy_worker_up{user=~\"$user\", worker=~\"$worker\"})",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Workers disconnect",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (user, worker) (increase(session_disconnect_count{user=~\"$user\"}[$__rate_interval]))",
     "legendFormat": "{{user}} - {{worker}}"
    }
   ]
  },
  {
   "title": "Share Validations (backend_outbound_shares)",
   "type": "graph",
   "description": "1m minimum intervals stacked bar chart showing proportion of valid, invalid, and stale shares.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (share_type)(increase(backend_outbound_shares{user=~\"$user\", worker=~\"$worker\"}[$__interval])) / ignoring(share_type) group_left sum(increase(backend_outbound_shares{user=~\"$user\", worker=~\"$worker\"}[$__interval]))",
     "legendFormat": "{{share_type}}"
    }
   ]
  },
  {
   "title": "Total Outbound Hashrate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "THs" } },
   "yaxes": [
    { "format": "THs" }
   ],
   "targets": [
    {
     "expr": "(sum by (share_type) (rate(backend_outbound_shares_diff{user=~\"$user\", worker=~\"$worker\"}[$__interval])) * 2 ^ 32 / 1e12) != 0",
     "legendFormat": "{{share_type}}"
    }
   ]
  }
 ]
}